# Site settings
title: Inicio
theme: jekyll-theme-cayman

author:
  name: Ignacio Garcia Pizales
  email: ignaciogp08@gmail.com
  
description: "Consultoría desarrollo web"

# Build settings
remote_theme: jekyll/minima
